### ISSUE TITLE
Request to add attribution for Logo.png image as per CC BY 4.0 in README.md

### ISSUE THREAD

**Issue by susam** [Dhghomon/programming_at_40#1]
Hi @Dhghomon,

The article in the [README.md](https://github.com/Dhghomon/programming_at_40/blob/master/README.md) is great. I enjoyed reading it.

While reading your article, I came across the [Logo.png](https://github.com/Dhghomon/programming_at_40/blob/master/Logo.png) image that you are using in this article. It appears you may have picked this image from the [Wikipedia article on Logo](https://en.wikipedia.org/wiki/Logo_(programming_language)).

This image was created by me and published on Wikipedia under the Creative Commons Attribution 4.0 International license. Please see https://en.wikipedia.org/wiki/File:IBM_LCSI_Logo_Circles.png for more details. The image is free to use and share, however, as per the terms of the license, I request you to add attribution for the image. I would appreciate if you please add a little note below the image that says something to the following effect:

```
Image by @susam under the terms of [CC BY 4.0](https://creativecommons.org/licenses/by/4.0/).
```

Please let me know if you have any questions or concerns.

Thanks,
Susam

**Comment by Dhghomon** [comment]
So you're the person who was inspired by Logo! You know, if that competition never took place I probably would have had fonder memories of it too. I added the CC notice as requested.

**Comment by susam** [comment]
Thank you, @Dhghomon! 🙂
